version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - sam package --template-file pua-wei-xin-cloud-resume-challenge.yml --s3-bucket pua-wei-xin-cloud-resume-challenge --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml